version: '3'

services:  
  alpine_php:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: alpine_php
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

  web:
    image: nginx:latest
    container_name: nginx_alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - alpine_php
    ports:
      - "80:80"
    volumes_from:
      - alpine_php